all:
  is_secure:   true

list:
  is_secure:   true
  credentials: [[user_list_view,user_list_edit]]

edit:
  is_secure:   true
  credentials: user_list_edit
      
update:
  is_secure:   true
  credentials: user_list_edit

delete:
  is_secure:   true
  credentials: user_list_edit
    
listActionsRemoveUser:
  is_secure:   true
  credentials: user_list_edit

listActionsUserStatus:
  is_secure:   true
  credentials: user_list_edit
  